package com.gtocore.data.lang;

import com.gtocore.client.Tooltips;

import com.gtolib.utils.ItemUtils;

import com.gregtechceu.gtceu.api.GTValues;

import static com.gtocore.data.lang.LangHandler.addCNEN;
import static net.minecraft.ChatFormatting.GOLD;
import static net.minecraft.ChatFormatting.RESET;

final class ItemLang {

    public static void init() {
        addCNEN("item.gtceu.circuits", "电路", "Circuits");
        for (int i = 0; i < 15; i++) {
            addCNEN("tag.item.gtceu.circuits." + GTValues.VN[i].toLowerCase(), GTValues.VN[i] + "电路", GTValues.VN[i] + " Circuit");
        }

        Tooltips.TOOL_TIPS_MAP.forEach((i, s) -> {
            for (int j = 0; j < s.length(); j++) {
                addCNEN("gtocore.tooltip.item." + ItemUtils.getIdLocation(i).getPath() + "." + j, s.cns()[j], s.ens()[j]);
            }
        });

        addCNEN("item.gtceu.long_rod_extruder_mold", "模头（长杆）", "Extruder Mold (Long Rod)");

        addCNEN("tagprefix.living_rock", "活%s矿石", "Living %s Ore");
        addCNEN("tagprefix.gloomslate", "幽暗%s矿石", "Gloomslate %s Ore");
        addCNEN("tagprefix.sculk_stone", "幽匿%s矿石", "Sculk %s Ore");
        addCNEN("tagprefix.ceres_stone", "谷神星%s矿石", "Ceres %s Ore");
        addCNEN("tagprefix.contaminable_nanites", "污染的%s纳米蜂群", "Contaminable %s Nano Swarm");
        addCNEN("tagprefix.enceladus_stone", "土卫二%s矿石", "Enceladus %s Ore");
        addCNEN("tagprefix.ganymede_stone", "木卫三%s矿石", "Ganymede %s Ore");
        addCNEN("tagprefix.glacio_stone", "霜原石%s矿石", "Glacio %s Ore");
        addCNEN("tagprefix.io_stone", "木卫一%s矿石", "Io %s Ore");
        addCNEN("tagprefix.mars_stone", "火星%s矿石", "Mars %s Ore");
        addCNEN("tagprefix.mercury_stone", "水星%s矿石", "Mercury %s Ore");
        addCNEN("tagprefix.milled", "碾磨%s", "Milled %s");
        addCNEN("tagprefix.moon_stone", "月石%s矿石", "Moon %s Ore");
        addCNEN("tagprefix.nanites", "%s纳米蜂群", "%s Nano Swarm");
        addCNEN("tagprefix.pluto_stone", "冥王星%s矿石", "Pluto %s Ore");
        addCNEN("tagprefix.titan_stone", "土卫六%s矿石", "Titan %s Ore");
        addCNEN("tagprefix.venus_stone", "金星%s矿石", "Venus %s Ore");
        addCNEN("tagprefix.curved_plate", "弯曲%s板", "Curved %s Plate");
        addCNEN("tagprefix.motor_enclosure", "%s马达外壳", "%s Motor Enclosure");
        addCNEN("tagprefix.pump_barrel", "%s泵筒", "%s Pump Barrel");
        addCNEN("tagprefix.piston_housing", "%s活塞壳体", "%s Piston Housing");
        addCNEN("tagprefix.emitter_base", "%s发射器基底", "%s Emitter Base");
        addCNEN("tagprefix.sensor_casing", "%s传感器外壳", "%s Sensor Casing");
        addCNEN("tagprefix.field_generator_casing", "%s力场发生器外壳", "%s Field Generator Casing");
        addCNEN("tagprefix.rough_blank", "%s粗坯", "%s Rough Blank");
        addCNEN("tagprefix.brick", "%s砖", "%s Brick");
        addCNEN("tagprefix.flake", "%s薄片", "%s Flake");
        addCNEN("tagprefix.catalyst", "%s催化剂", "%s Catalyst");
        addCNEN("tagprefix.artificial_gem", "人造%s", "Artificial %s");
        addCNEN("tagprefix.crystal_seed", "%s晶种", "%s Crystal Seed");
        addCNEN("tagprefix.superconductor_base", "%s超导粗胚", "%s Superconductor Base");

        addCNEN("gtocore.tooltip.artificial_gem", "比自然的更好", "Better than nature");
        addCNEN("gtocore.tooltip.unknown", "未知", "Unknown");

        addCNEN("item.gtceu.tool.hv_vajra", "%s 基础金刚杵", "%s Basic Vajra");
        addCNEN("item.gtceu.tool.ev_vajra", "%s 高级金刚杵", "%s Advanced Vajra");
        addCNEN("item.gtceu.tool.iv_vajra", "%s 终极金刚杵", "%s Ultimate Vajra");
        addCNEN("gtocore.tooltip.item.kinetic_rotor.max", "最大风力: %s", "Max Wind Speed: %s");
        addCNEN("gtocore.tooltip.item.kinetic_rotor.min", "最小风力: %s", "Min Wind Speed: %s");
        addCNEN("gtocore.tooltip.item.virtual_item_provider", "为机器的虚拟电路槽提供物品", "Provide items for the machine's virtual circuit slot.");

        addCNEN("gtocore.tooltip.item.really_max_battery", "填满它就能通关GregTechCEu Modern", "Filling it up can allow you to complete GregTechCEu Modern");
        addCNEN("gtocore.tooltip.item.transcendent_max_battery", "填满它就能通关GregTech Odyssey", "Filling it up can allow you to complete GregTech Odyssey");
        addCNEN("gtocore.tooltip.item.extremely_max_battery", "有生之年将它填满", "Fill it up within your lifetime");
        addCNEN("gtocore.tooltip.item.insanely_max_battery", "填满也就图一乐", "Filling it up is just for fun");
        addCNEN("gtocore.tooltip.item.mega_max_battery", "填满电池 机械飞升", "Fill up the battery for mechanical ascension");
        addCNEN("gtocore.tooltip.item.tier_circuit", "%s级电路", "%s Tier Circuit");
        addCNEN("gtocore.tooltip.item.suprachronal_circuit", "运行在已知时空之外", "Running outside of known spacetime");
        addCNEN("gtocore.tooltip.item.magneto_resonatic_circuit", "利用磁共振仪器产生的强大磁场来运行", "Utilize the powerful magnetic field generated by magnetic resonance instruments to operate");
        addCNEN("gtocore.tooltip.item.universal_circuit", "一个通用的电路", "A universal circuit");
        addCNEN("gtocore.tooltip.item.craft_step", "合成步骤：%s", "Craft Step: %s");

        addCNEN("item.gtocore.structure_detect.error.0", "需要在 %s:", "Required at %s:");
        addCNEN("item.gtocore.structure_detect.error.1", "在 %s:", "At %s:");
        addCNEN("item.gtocore.structure_detect.error.2", "[%s, %s, %s]", "[%s, %s, %s]");
        addCNEN("item.gtocore.structure_detect.tooltip.0", "潜行右键主方块以检测多方块结构", "Sneak right-click the main block to detect multiblock structure.");
        addCNEN("item.gtocore.structure_detect.tooltip.1", "检测大型结构时可能会有延迟", "There may be lag when detecting large structures.");
        addCNEN("item.gtocore.disc.data", "光盘数据：%s", "Disc data: %s");

        addCNEN("item.gtocore.order.config", "订单配置", "Order Config");

        addCNEN("item.gtocore.data_item.type.title", "§n%s配方数据：", "§n%s Recipes Data:");
        addCNEN("gtocore.tooltip.item.empty_data", "§n空数据：", "§nEmpty Data:");
        addCNEN("gtocore.tooltip.item.empty_serial", "- §a编号：%s", "- §aNumber: %s");
        addCNEN("gtocore.tooltip.item.scanning_data", "§n扫描数据：", "§nScan Data:");
        addCNEN("gtocore.tooltip.item.scanned_things", "- %d× %s", "- %d× %s");
        addCNEN("gtocore.tooltip.item.scanning_serial", "- §a扫描编号：%s", "- §aScan number: %s");
        addCNEN("gtocore.tooltip.item.analyze_data", "§n研究数据：", "§nResearch data:");
        addCNEN("gtocore.tooltip.item.analyze_things", "- %d", "- %d");
        addCNEN("gtocore.tooltip.item.analyze_serial", "- §a研究编号：%s", "- §aResearch number: %s");

        addCNEN("gtocore.behaviour.grass_harvest.description", GOLD + "极大" + RESET + "地提升小麦种子掉落概率", GOLD + "Greatly" + RESET + " increase the probability of wheat seed dropping");
        addCNEN("gtocore.behaviour.grass_harvest.description2", "右键以收割", "Right click to harvest");

        addCNEN("gtocore.tooltip.item.prospector.mana.1", "魔力: §b%s§r / §a%s§r ",
                "Mana: §b%s§r / §a%s§r ");
        addCNEN("gtocore.tooltip.item.prospector.mana.2", "（§b%s§r / §a%s§r 个魔力池）",
                "（§b%s§r / §a%s§r Mana Pools）");

        addCNEN("gtocore.tooltip.item.machine_coordinate_card.tooltip.1", "右键机器记录其坐标，右键空气清空记录。",
                "Right-click a machine to record its coordinates, right-click air to clear the record");
        addCNEN("gtocore.tooltip.item.machine_coordinate_card.tooltip.2", "§6记录信息：§r%s§b(%s§b, %s§b, %s§b)",
                "§6Coordinate Info: §r%s§b(%s§b, %s§b, %s§b)");
    }
}
